version: 0.0
os: linux
files:
  - source: /
    destination: /home/wineseeker/backend

permissions:
  - object: /home/wineseeker/backend
    owner: wineseeker
    group: wineseeker

hooks:
  AfterInstall:
    - location: shell-scripts/after_install.sh
      timeout: 300
      runas: wineseeker
  ApplicationStart:
    - location: shell-scripts/start_server.sh
      timeout: 300
      runas: wineseeker