version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm ci
      - filename=".env"
      - touch $filename
      - echo DATABASE_URL=$(aws ssm get-parameters --names $path"/wine-seeker/backend/production/DATABASE_URL" --query Parameters[0].Value | sed 's/"//g') > $filename
      - echo echo SMTP_HOST=$(aws ssm get-parameters --names $path"/wine-seeker/backend/production/SMTP_HOST" --query Parameters[0].Value | sed 's/"//g') >> $filename
      - echo SMTP_FROM_ADDRESS=$(aws ssm get-parameters --names $path"/wine-seeker/backend/production/SMTP_FROM_ADDRESS" --query Parameters[0].Value | sed 's/"//g') >> $filename
      - echo SMTP_PORT=$(aws ssm get-parameters --names $path"/wine-seeker/backend/production/SMTP_PORT" --query Parameters[0].Value | sed 's/"//g') >> $filename
      - echo SMTP_SECURE=$(aws ssm get-parameters --names $path"/wine-seeker/backend/production/SMTP_SECURE" --query Parameters[0].Value | sed 's/"//g') >> $filename
      - echo SMTP_USER=$(aws ssm get-parameters --names $path"/wine-seeker/backend/production/SMTP_USER" --query Parameters[0].Value | sed 's/"//g') >> $filename
      - echo SMTP_PASSWORD=$(aws ssm get-parameters --names $path"/wine-seeker/backend/production/SMTP_PASSWORD" --query Parameters[0].Value | sed 's/"//g') >> $filename
      - npx prisma generate
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'