-- AlterTable
ALTER TABLE `user` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `leaved` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `leavedAt` DATETIME(3) NULL,
    MODIFY `email` VARCHAR(191) NULL;
